CREATE TABLE postdata ( 
  id      INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  val     varchar(16),
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
